import os

ID_CLIENT = os.environ.get("ID_CLIENT")
SECRET_CLIENT = os.environ.get("SECRET_CLIENT")

MES_PERSONNAGES = [
    # --- Royaume : Confrérie du Thorium ---
    ('Absolya', 'confrérie-du-thorium'),
    ('Annahilahay', 'confrérie-du-thorium'),
    ('Arcorror', 'confrérie-du-thorium'),
    ('Aryastrasza', 'confrérie-du-thorium'),
    ('Daarken', 'confrérie-du-thorium'),
    ('Durmbaur', 'confrérie-du-thorium'),
    ('Djulzin', 'confrérie-du-thorium'),
    ('Ékorce', 'confrérie-du-thorium'),
    ('Féshine', 'confrérie-du-thorium'),
    ('Giin', 'confrérie-du-thorium'),
    ('Héphastrasza', 'confrérie-du-thorium'),
    ('Jakundar', 'confrérie-du-thorium'),
    ('Kakumô', 'confrérie-du-thorium'),
    ('Karkua', 'confrérie-du-thorium'),
    ('Kayssée', 'confrérie-du-thorium'),
    ('Khör', 'confrérie-du-thorium'),
    ('Méduzah', 'confrérie-du-thorium'),
    ('Pandréa', 'confrérie-du-thorium'),
    ('Phéniraë', 'confrérie-du-thorium'),
    ('Rytaa', 'confrérie-du-thorium'),
    ('Scindios', 'confrérie-du-thorium'),
    ('Sélunée', 'confrérie-du-thorium'),
    ('Séphine', 'confrérie-du-thorium'),
    ('Sharelys', 'confrérie-du-thorium'),
    ('Syrra', 'confrérie-du-thorium'),
    ('Tönka', 'confrérie-du-thorium'),
    ('Tryxi', 'confrérie-du-thorium'),
    ('Vajunko', 'confrérie-du-thorium'),
    ('Wombaji', 'confrérie-du-thorium'),

    # --- Royaume : Les Sentinelles ---
    ('Ævanreth', 'les-sentinelles'),
    ('Akané', 'les-sentinelles'),
    ('Ayshaune', 'les-sentinelles'),
    ('Barloud', 'les-sentinelles'),
    ('Bélyal', 'les-sentinelles'),
    ('Blaîr', 'les-sentinelles'),
    ('Chutétoile', 'les-sentinelles'),
    ('Élizabeth', 'les-sentinelles'),
    ('Êv', 'les-sentinelles'),
    ('Feuraluyn', 'les-sentinelles'),
    ('Furaya', 'les-sentinelles'),
    ('Gydera', 'les-sentinelles'),
    ('Haghéra', 'les-sentinelles'),
    ('Havväh', 'les-sentinelles'),
    ('Linilym', 'les-sentinelles'),
    ('Lylìth', 'les-sentinelles'),
    ('Narîdia', 'les-sentinelles'),
    ('Nasharz', 'les-sentinelles'),
    ('Neekrad', 'les-sentinelles'),
    ('Névègosa', 'les-sentinelles'),
    ('Nymphaë', 'les-sentinelles'),
    ('Purités', 'les-sentinelles'),
    ('Ranulia', 'les-sentinelles'),
    ('Rengarh', 'les-sentinelles'),
    ('Scarêvansse', 'les-sentinelles'),
    ('Shiden', 'les-sentinelles'),
    ('Synestrah', 'les-sentinelles'),
    ('Vrenfel', 'les-sentinelles'),
]